In [1]:
import numpy as np
import pandas as pd

In [2]:
!pip install scikit-learn==1.2.2

  Using cached scikit_learn-1.2.2-cp39-cp39-macosx_12_0_arm64.whl (8.5 MB)
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.4.0
    Uninstalling scikit-learn-1.4.0:
      Successfully uninstalled scikit-learn-1.4.0


In [3]:
df = pd.read_csv('https://github.com/pvateekul/2110446_DSDE_2023s2/raw/main/DataSet/hed2020_dataset.csv')

In [4]:
df

id label cap-shape cap-surface bruises odor gill-attachment  \
0        1     p         x           s       t    p               f   
1        2     e         x           s       t    a               f   
2        3     e         b           s       t    l               f   
3        4     p         x           y       t    p               f   
4        5     e         x           s       f    n               f   
...    ...   ...       ...         ...     ...  ...             ...   
5819  5820     e         k           s       f    n               a   
5820  5821     e         x           s       f    n               a   
5821  5822     e         f           s       f    n               a   
5822  5823     p         k           y       f    y               f   
5823  5824     e         x           s       f    n               a   

     gill-spacing gill-size stalk-shape  ... ring-number ring-type  \
0               c         n           e  ...           o         p   
1               c         b           e  ...           o         p   
2               c         b           e  ...           o         p   
3               c         n           e  ...           o         p   
4               w         b           t  ...           o         e   
...           ...       ...         ...  ...         ...       ...   
5819            c         b           e  ...           o         p   
5820            c         b           e  ...           o         p   
5821            c         b           e  ...           o         p   
5822            c         n           t  ...           o         e   
5823            c         b           e  ...           o         p   

     spore-print-color population habitat cap-color-rate gill-color-rate  \
0                    k          s       u            1.0             3.0   
1                    n          n       g            2.0             3.0   
2                    n          n       m            3.0             1.0   
3                    k          s       u            3.0             1.0   
4                    n          a       g            4.0             3.0   
...                ...        ...     ...            ...             ...   
5819                 b          c       l            1.0            10.0   
5820                 b          v       l            1.0            10.0   
5821                 b          c       l            1.0             1.0   
5822                 w          v       l            1.0             9.0   
5823                 o          c       l            1.0            10.0   

     veil-color-rate stalk-color-above-ring-rate  stalk-color-below-ring-rate  
0                1.0                         1.0                          1.0  
1                1.0                         1.0                          1.0  
2                1.0                         1.0                          1.0  
3                1.0                         1.0                          1.0  
4                1.0                         1.0                          1.0  
...              ...                         ...                          ...  
5819             2.0                         7.0                          8.0  
5820             1.0                         7.0                          8.0  
5821             2.0                         7.0                          8.0  
5822             1.0                         1.0                          1.0  
5823             2.0                         7.0                          8.0  

[5824 rows x 24 columns]

In [5]:
df = df[df.label == 'e']

df

id label cap-shape cap-surface bruises odor gill-attachment  \
1        2     e         x           s       t    a               f   
2        3     e         b           s       t    l               f   
4        5     e         x           s       f    n               f   
5        6     e         x           y       t    a               f   
6        7     e         b           s       t    a               f   
...    ...   ...       ...         ...     ...  ...             ...   
5815  5816     e         x           s       f    n               a   
5819  5820     e         k           s       f    n               a   
5820  5821     e         x           s       f    n               a   
5821  5822     e         f           s       f    n               a   
5823  5824     e         x           s       f    n               a   

     gill-spacing gill-size stalk-shape  ... ring-number ring-type  \
1               c         b           e  ...           o         p   
2               c         b           e  ...           o         p   
4               w         b           t  ...           o         e   
5               c         b           e  ...           o         p   
6               c         b           e  ...           o         p   
...           ...       ...         ...  ...         ...       ...   
5815            c         b           e  ...           o         p   
5819            c         b           e  ...           o         p   
5820            c         b           e  ...           o         p   
5821            c         b           e  ...           o         p   
5823            c         b           e  ...           o         p   

     spore-print-color population habitat cap-color-rate gill-color-rate  \
1                    n          n       g            2.0             3.0   
2                    n          n       m            3.0             1.0   
4                    n          a       g            4.0             3.0   
5                    k          n       g            2.0             1.0   
6                    k          n       m            3.0             2.0   
...                ...        ...     ...            ...             ...   
5815                 o          v       l            1.0            10.0   
5819                 b          c       l            1.0            10.0   
5820                 b          v       l            1.0            10.0   
5821                 b          c       l            1.0             1.0   
5823                 o          c       l            1.0            10.0   

     veil-color-rate stalk-color-above-ring-rate  stalk-color-below-ring-rate  
1                1.0                         1.0                          1.0  
2                1.0                         1.0                          1.0  
4                1.0                         1.0                          1.0  
5                1.0                         1.0                          1.0  
6                1.0                         1.0                          1.0  
...              ...                         ...                          ...  
5815             2.0                         7.0                          8.0  
5819             2.0                         7.0                          8.0  
5820             1.0                         7.0                          8.0  
5821             2.0                         7.0                          8.0  
5823             2.0                         7.0                          8.0  

[2104 rows x 24 columns]

In [6]:
selected_variables = ['cap-color-rate', 'stalk-color-above-ring-rate']
df = df[selected_variables]
df


cap-color-rate  stalk-color-above-ring-rate
1                2.0                          1.0
2                3.0                          1.0
4                4.0                          1.0
5                2.0                          1.0
6                3.0                          1.0
...              ...                          ...
5815             1.0                          7.0
5819             1.0                          7.0
5820             1.0                          7.0
5821             1.0                          7.0
5823             1.0                          7.0

[2104 rows x 2 columns]

In [7]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
df_impute = imputer.fit_transform(df)

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_impute)

df_scaled


array([[-0.73500484, -0.74760802],
       [-0.23417985, -0.74760802],
       [ 0.26664515, -0.74760802],
       ...,
       [-1.23582983,  2.43279003],
       [-1.23582983,  2.43279003],
       [-1.23582983,  2.43279003]])

In [9]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=2020)
kmeans.fit(df_scaled)
cluster_labels = kmeans.labels_

cluster_labels


/Users/jackkahod/anaconda3/envs/datasci/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([2, 0, 0, ..., 1, 1, 1], dtype=int32)

In [10]:
centroid = kmeans.cluster_centers_
centroid


array([[ 0.41361805, -0.37536859],
       [-1.23582983,  2.30658376],
       [-1.22906193, -0.29354739],
       [ 2.5059661 , -0.74760802],
       [ 1.2093128 ,  1.90272369]])

In [11]:
centroid_original_scale = scaler.inverse_transform(centroid)
centroid_original_scale

array([[4.2934616 , 1.70225065],
       [1.        , 6.76190476],
       [1.01351351, 1.85661095],
       [8.47126437, 1.        ],
       [5.88222965, 6.        ]])