## Import

In [2]:
import numpy as np
import pandas as pd

## Load data

In [3]:
df = pd.read_csv("https://github.com/kaopanboonyuen/2110446_DataScience_2021s2/raw/main/datasets/msff_rv22v1_1.csv")

In [4]:
df.head()

Artist Name                             Track Name  Popularity  \
0             Bruno Mars  That's What I Like (feat. Gucci Mane)        60.0   
1                 Boston                           Hitch a Ride        54.0   
2          The Raincoats                     No Side to Fall In        35.0   
3                   Deno             Lingo (feat. J.I & Chunkz)        66.0   
4  Red Hot Chili Peppers      Nobody Weird Like Me - Remastered        53.0   

   danceability  energy   key  loudness  mode  speechiness  acousticness  \
0         0.854   0.564   1.0    -4.964     1       0.0485      0.017100   
1         0.382   0.814   3.0    -7.230     1       0.0406      0.001100   
2         0.434   0.614   6.0    -8.334     1       0.0525      0.486000   
3         0.853   0.597  10.0    -6.528     0       0.0555      0.021200   
4         0.167   0.975   2.0    -4.279     1       0.2160      0.000169   

   instrumentalness  liveness  valence    tempo  duration_in min/ms  \
0               NaN    0.0849   0.8990  134.071            234596.0   
1          0.004010    0.1010   0.5690  116.454            251733.0   
2          0.000196    0.3940   0.7870  147.681            109667.0   
3               NaN    0.1220   0.5690  107.033            173968.0   
4          0.016100    0.1720   0.0918  199.060            229960.0   

   time_signature  Class  
0               4      5  
1               4     10  
2               4      6  
3               4      5  
4               4     10

## Q1.1

In [5]:
variable_to_drop = ["Artist Name", "Track Name", "Popularity"]
df_drop = df.drop(variable_to_drop, axis=1)

In [6]:
df_drop.head()

danceability  energy   key  loudness  mode  speechiness  acousticness  \
0         0.854   0.564   1.0    -4.964     1       0.0485      0.017100   
1         0.382   0.814   3.0    -7.230     1       0.0406      0.001100   
2         0.434   0.614   6.0    -8.334     1       0.0525      0.486000   
3         0.853   0.597  10.0    -6.528     0       0.0555      0.021200   
4         0.167   0.975   2.0    -4.279     1       0.2160      0.000169   

   instrumentalness  liveness  valence    tempo  duration_in min/ms  \
0               NaN    0.0849   0.8990  134.071            234596.0   
1          0.004010    0.1010   0.5690  116.454            251733.0   
2          0.000196    0.3940   0.7870  147.681            109667.0   
3               NaN    0.1220   0.5690  107.033            173968.0   
4          0.016100    0.1720   0.0918  199.060            229960.0   

   time_signature  Class  
0               4      5  
1               4     10  
2               4      6  
3               4      5  
4               4     10

## Q1.2

In [7]:
selected_df = df_drop.rename(columns={"duration_in min/ms": "duration"})

## Q1.3

In [8]:
selected_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17996 entries, 0 to 17995
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   danceability      17996 non-null  float64
 1   energy            17996 non-null  float64
 2   key               15982 non-null  float64
 3   loudness          17996 non-null  float64
 4   mode              17996 non-null  int64  
 5   speechiness       17996 non-null  float64
 6   acousticness      17996 non-null  float64
 7   instrumentalness  13619 non-null  float64
 8   liveness          17996 non-null  float64
 9   valence           17996 non-null  float64
 10  tempo             17996 non-null  float64
 11  duration          17996 non-null  float64
 12  time_signature    17996 non-null  int64  
 13  Class             17996 non-null  int64  
dtypes: float64(11), int64(3)
memory usage: 1.9 MB


## Q2.1

### I use one-way ANOVA

In [13]:
from statistics import mean
from scipy.stats import f_oneway

groups = []
for genre, group_data in selected_df.groupby('Class')['valence']:
    print(f"Genre: {genre}, mean: {mean(group_data)}")
    groups.append(group_data)

# print(groups)

Genre: 0, mean: 0.38268416
Genre: 1, mean: 0.5054004369992716
Genre: 2, mean: 0.612596462264151
Genre: 3, mean: 0.6270753731343284
Genre: 4, mean: 0.612764857881137
Genre: 5, mean: 0.545973807878369
Genre: 6, mean: 0.48747197526092
Genre: 7, mean: 0.2295888888888889
Genre: 8, mean: 0.3200309061488673
Genre: 9, mean: 0.521298969889065
Genre: 10, mean: 0.4962245706203273


In [12]:
f_statistic, p_value = f_oneway(*groups)

alpha = 0.05

print(f"F-statistic: {f_statistic}")
print(f"p-value: {p_value}")

if p_value < alpha:
    print("Reject the null hypothesis")
    print("There are significant differences between groups")
else:
    print("Fail to reject the null hypothesis")
    print("There are no significant differences between groups")

F-statistic: 279.4143448989305
p-value: 0.0
Reject the null hypothesis
There are significant differences between groups


## Q3.1

In [18]:
null_count = selected_df.isnull().sum()
print(null_count)

danceability           0
energy                 0
key                 2014
loudness               0
mode                   0
speechiness            0
acousticness           0
instrumentalness    4377
liveness               0
valence                0
tempo                  0
duration               0
time_signature         0
Class                  0
dtype: int64


In [20]:
print(f"Missing records for 'key' is {null_count['key']}\nMissing records for 'instrumentalness' is {null_count['instrumentalness']}")

Missing records for 'key' is 2014
Missing records for 'instrumentalness' is 4377


## Q3.2

In [21]:
selected_df_fill_key = selected_df.fillna({"key": 1})

In [23]:
null_count = selected_df_fill_key.isnull().sum()
print(f"Missing records for 'key' is {null_count['key']}")

Missing records for 'key' is 0


## Q3.3

In [25]:
selected_df_fill_instrumentalness = selected_df_fill_key.fillna({"instrumentalness": 0})

selected_df_fill_instrumentalness["instrumentalness"] = selected_df_fill_instrumentalness["instrumentalness"].apply(lambda x: 0 if x < 0.01 else x)

In [26]:
null_count = selected_df_fill_instrumentalness.isnull().sum()
print(f"Missing records for 'instrumentalness' is {null_count['instrumentalness']}")

Missing records for 'instrumentalness' is 0


## Q3.4

In [29]:
print(len(selected_df_fill_instrumentalness['key'].unique()))

11


In [31]:
df_dummy = pd.get_dummies(selected_df_fill_instrumentalness, columns=['key'], drop_first=True)

In [32]:
df_dummy.head()

danceability  energy  loudness  mode  speechiness  acousticness  \
0         0.854   0.564    -4.964     1       0.0485      0.017100   
1         0.382   0.814    -7.230     1       0.0406      0.001100   
2         0.434   0.614    -8.334     1       0.0525      0.486000   
3         0.853   0.597    -6.528     0       0.0555      0.021200   
4         0.167   0.975    -4.279     1       0.2160      0.000169   

   instrumentalness  liveness  valence    tempo  ...  key_2.0  key_3.0  \
0            0.0000    0.0849   0.8990  134.071  ...    False    False   
1            0.0000    0.1010   0.5690  116.454  ...    False     True   
2            0.0000    0.3940   0.7870  147.681  ...    False    False   
3            0.0000    0.1220   0.5690  107.033  ...    False    False   
4            0.0161    0.1720   0.0918  199.060  ...     True    False   

   key_4.0  key_5.0  key_6.0  key_7.0  key_8.0  key_9.0  key_10.0  key_11.0  
0    False    False    False    False    False    False     False     False  
1    False    False    False    False    False    False     False     False  
2    False    False     True    False    False    False     False     False  
3    False    False    False    False    False    False      True     False  
4    False    False    False    False    False    False     False     False  

[5 rows x 23 columns]

In [39]:
df_dummy.columns

Index(['danceability', 'energy', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration', 'time_signature', 'Class', 'key_2.0', 'key_3.0', 'key_4.0',
       'key_5.0', 'key_6.0', 'key_7.0', 'key_8.0', 'key_9.0', 'key_10.0',
       'key_11.0'],
      dtype='object')

## Q3.5

In [35]:
cleaned_df = df_dummy

In [36]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17996 entries, 0 to 17995
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   danceability      17996 non-null  float64
 1   energy            17996 non-null  float64
 2   loudness          17996 non-null  float64
 3   mode              17996 non-null  int64  
 4   speechiness       17996 non-null  float64
 5   acousticness      17996 non-null  float64
 6   instrumentalness  17996 non-null  float64
 7   liveness          17996 non-null  float64
 8   valence           17996 non-null  float64
 9   tempo             17996 non-null  float64
 10  duration          17996 non-null  float64
 11  time_signature    17996 non-null  int64  
 12  Class             17996 non-null  int64  
 13  key_2.0           17996 non-null  bool   
 14  key_3.0           17996 non-null  bool   
 15  key_4.0           17996 non-null  bool   
 16  key_5.0           17996 non-null  bool  

## Q3.6

In [37]:
cleaned_df.describe()

danceability        energy      loudness          mode   speechiness  \
count  17996.000000  17996.000000  17996.000000  17996.000000  17996.000000   
mean       0.543433      0.662777     -7.910660      0.636753      0.079707   
std        0.166268      0.235373      4.049151      0.480949      0.083576   
min        0.059600      0.000020    -39.952000      0.000000      0.022500   
25%        0.432000      0.509000     -9.538000      0.000000      0.034800   
50%        0.545000      0.700000     -7.016000      1.000000      0.047400   
75%        0.659000      0.860000     -5.189000      1.000000      0.083000   
max        0.989000      1.000000      1.355000      1.000000      0.955000   

       acousticness  instrumentalness      liveness       valence  \
count  17996.000000      17996.000000  17996.000000  17996.000000   
mean       0.247082          0.133880      0.196170      0.486208   
std        0.310632          0.275487      0.159212      0.240195   
min        0.000000          0.000000      0.011900      0.018300   
25%        0.004300          0.000000      0.097500      0.297000   
50%        0.081400          0.000000      0.129000      0.481000   
75%        0.434000          0.056600      0.258000      0.672000   
max        0.996000          0.996000      1.000000      0.986000   

              tempo      duration  time_signature         Class  
count  17996.000000  1.799600e+04    17996.000000  17996.000000  
mean     122.623294  2.007445e+05        3.924039      6.695821  
std       29.571527  1.119891e+05        0.361618      3.206073  
min       30.557000  5.016500e-01        1.000000      0.000000  
25%       99.620750  1.663370e+05        4.000000      5.000000  
50%      120.065500  2.091600e+05        4.000000      8.000000  
75%      141.969250  2.524900e+05        4.000000     10.000000  
max      217.416000  1.477187e+06        5.000000     10.000000

## Q4.1

In [40]:
from sklearn.model_selection import train_test_split

X = cleaned_df.drop('Class', axis=1)
y = cleaned_df['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234, stratify=y)

## Q4.2

In [42]:
print("Whole dataset size:", cleaned_df.shape[0])
print("Train set size:", X_train.shape[0])
print("Test set size:", X_test.shape[0])

Whole dataset size: 17996
Train set size: 12597
Test set size: 5399


## Q5.1

In [47]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion='gini', max_depth=10, min_samples_leaf=10, random_state=1234)

In [48]:
tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=10, random_state=1234)

## Q5.2

In [50]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = tree.predict(X_test)

report = classification_report(y_test, y_pred, digits=4)
print("Classification report\n", report)

acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

Classification report
               precision    recall  f1-score   support

           0     0.5283    0.5989    0.5614       187
           1     0.2222    0.0243    0.0438       412
           2     0.3633    0.2539    0.2989       382
           3     0.5726    0.5537    0.5630       121
           4     0.3828    0.4224    0.4016       116
           5     0.6338    0.6221    0.6279       434
           6     0.3916    0.2513    0.3061       776
           7     0.8895    0.8844    0.8870       173
           8     0.5201    0.5108    0.5154       556
           9     0.4223    0.4993    0.4576       757
          10     0.4343    0.6121    0.5081      1485

    accuracy                         0.4675      5399
   macro avg     0.4874    0.4758    0.4701      5399
weighted avg     0.4500    0.4675    0.4451      5399

Accuracy: 0.46749398036673456


## Q6.1

In [68]:
X_train_crop = X_train[['acousticness','duration','instrumentalness','speechiness']]
X_test_crop = X_test[['acousticness','duration','instrumentalness','speechiness']]

X_train_crop.describe()

acousticness      duration  instrumentalness   speechiness
count  12597.000000  1.259700e+04      12597.000000  12597.000000
mean       0.247800  2.012054e+05          0.133998      0.079570
std        0.311189  1.126238e+05          0.275206      0.082718
min        0.000000  5.016500e-01          0.000000      0.022500
25%        0.004270  1.668410e+05          0.000000      0.034800
50%        0.081300  2.092130e+05          0.000000      0.047500
75%        0.438000  2.524930e+05          0.059100      0.082300
max        0.996000  1.477187e+06          0.996000      0.935000

## Q6.2

In [62]:
from sklearn.linear_model import LogisticRegression

reg = LogisticRegression(random_state=1992, solver='newton-cg')

reg.fit(X_train_crop, y_train)

/opt/homebrew/Caskroom/miniforge/base/envs/datasci/lib/python3.9/site-packages/scipy/optimize/_linesearch.py:466: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/opt/homebrew/Caskroom/miniforge/base/envs/datasci/lib/python3.9/site-packages/scipy/optimize/_linesearch.py:314: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/opt/homebrew/Caskroom/miniforge/base/envs/datasci/lib/python3.9/site-packages/sklearn/utils/optimize.py:210: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  warnings.warn(


LogisticRegression(random_state=1992, solver='newton-cg')

## Q6.3

In [63]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = reg.predict(X_test_crop)

report = classification_report(y_test, y_pred, digits=4)
print("Classification report\n", report)

acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

Classification report
               precision    recall  f1-score   support

           0     0.3729    0.7219    0.4918       187
           1     0.0000    0.0000    0.0000       412
           2     0.2414    0.0733    0.1124       382
           3     1.0000    0.0413    0.0794       121
           4     0.3022    0.5862    0.3988       116
           5     0.6497    0.5000    0.5651       434
           6     0.3815    0.1972    0.2600       776
           7     0.8020    0.9133    0.8541       173
           8     0.4233    0.1439    0.2148       556
           9     0.3038    0.1902    0.2340       757
          10     0.3727    0.7771    0.5038      1485

    accuracy                         0.3967      5399
   macro avg     0.4409    0.3768    0.3376      5399
weighted avg     0.3804    0.3967    0.3390      5399

Accuracy: 0.39674013706241895


/opt/homebrew/Caskroom/miniforge/base/envs/datasci/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniforge/base/envs/datasci/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniforge/base/envs/datasci/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

## 7.1

In [67]:
from sklearn.metrics import confusion_matrix
from scipy.stats import chi2_contingency

y_pred1 = tree.predict(X_test)
y_pred2 = reg.predict(X_test_crop)

cm1 = confusion_matrix(y_test, y_pred1)
cm2 = confusion_matrix(y_test, y_pred2)

a = cm1[0][1]  # False Positive for tree
b = cm1[1][0]  # False Negative for tree
c = cm2[0][1]  # False Positive for reg
d = cm2[1][0]  # False Negative for reg

contingency_table = [[a, b], [c, d]]

print(contingency_table)

print(chi2_contingency(contingency_table))

# chi2, p_value = chi2_contingency(contingency_table)

# alpha = 0.05  # significance level
# if p_value < alpha:
#    print("There is a significant difference between the two classifiers (reject null hypothesis)")
# else:
#    print("There is no significant difference between the two classifiers (fail to reject null hypothesis)")

[[112   0   0  20  31   0   0   9   0  10   5]
 [  0  10  20   0   0  26  73   0  24  67 192]
 [  0   2  97   0   0   7  42   0   7  70 157]
 [ 26   0   0  67   8   0   0  10   0   4   6]
 [ 23   0   0   6  49   0   0   0   0  31   7]
 [  0   0   7   0   0 270  30   0   1  72  54]
 [  0  25  55   0   0  31 195   0  34  96 340]
 [ 11   0   0   8   1   0   0 153   0   0   0]
 [  0   1   7   0   0   0  31   0 284   8 225]
 [ 22   1  20   8  30  69  25   0   6 378 198]
 [ 18   6  61   8   9  23 102   0 190 159 909]]
[[ 135    0    0    0   29    0    0   23    0    0    0]
 [   0    0   10    0    0   20   55    0   15   33  279]
 [   0    0   28    0    0    4   33    0    7   87  223]
 [ 101    0    0    5    4    0    0   11    0    0    0]
 [  47    0    0    0   68    0    0    1    0    0    0]
 [   0    0    4    0    0  217   10    0    4   36  163]
 [   0    0   19    0    0   17  153    0   31   79  477]
 [  15    0    0    0    0    0    0  158    0    0    0]
 [   0    0    5  

/opt/homebrew/Caskroom/miniforge/base/envs/datasci/lib/python3.9/site-packages/scipy/stats/contingency.py:134: RuntimeWarning: invalid value encountered in divide
  expected = reduce(np.multiply, margsums) / observed.sum() ** (d - 1)
